apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-{{ .Release.Name  }}
  name: nginx-{{ .Release.Name  }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx-{{ .Release.Name  }}
  template:
    metadata:
      labels:
        app: nginx-{{ .Release.Name  }}
    spec:
      containers:
      - image: nginx
        name: nginx
