apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    api: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      api: {{ .Release.Name }}
  template:
    metadata:
      labels:
        api: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Release.Name }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: github-secret
