apiVersion: v1
kind: Service
metadata:
  labels:
    api: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  externalIPs:
    - "144.22.147.130"
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    api: {{ .Release.Name }}
  type: NodePort
